name: next_wisher
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+5
#1(1.0.0)

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: 
  flutter_screenutil: 
  logger: 
  get_storage:
  http: 
  intl:
  flutter_spinkit: 
  dropdown_button2:
  lottie: 
  connectivity_plus:
  fluttertoast: 
  google_fonts:
  cached_network_image:
  flutter_animate:
  flutter_svg:
  flutter_inappwebview:
  flutter_rating:
  flutter_widget_from_html: 
  file_picker: 
  image_picker: 
  permission_handler: 
  video_player: 
  chewie: 
  appinio_video_player: 
  badges: 
  path_provider: 
  device_info_plus:
  rename_app: 
#  icons_launcher: ^3.0.0
  flutter_launcher_icons: 
  firebase_core:
  firebase_messaging:
  uuid:
  flutter_local_notifications:
  shimmer:

dev_dependencies:
  icons_launcher: ^3.0.1
  flutter_test:
    sdk: flutter
icons_launcher:
    image_path: 'assets/andriodappicon.jpg'
    platforms:
      android:
        enable: true
        image_path: 'assets/andriodappicon.jpg'
        notification_image: "assets/andriodappicon.jpg"
        # adaptive_background_color: '#ffffff'
        adaptive_background_image: 'assets/andriodappicon.jpg'
        adaptive_foreground_image: 'assets/andriodappicon.jpg'
        adaptive_round_image: 'assets/andriodappicon.jpg'
        adaptive_monochrome_image: 'assets/andriodappicon.jpg'
      ios:
        enable: true
        image_path: 'assets/andriodappicon.jpg'
        # For iOS 18+ (support dark and tinted)
        dark_path: "assets/andriodappicon.jpg"
        tinted_path: "assets/andriodappicon.jpg"
      web:
        enable: true
        image_path: 'assets/andriodappicon.jpg'
        favicon_path: 'assets/andriodappicon.jpg'

flutter_lints:
  change_app_package_name: ^1.4.0
#  com.example.next_wisher => com.nextwisher.app

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  assets:
    - assets/
    - assets/categories/
    - assets/country/
    - assets/email_verification.png
    - assets/playstore.png

