// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'next_wisher';
  static const String PROJECT_VERSION = '1.1.0+5';
  static const String ANDRIODAPPICON = 'assets/andriodappicon.jpg';
  static const String BG = 'assets/bg.png';
  static const String BG_SEARCH = 'assets/bg_search.png';
  static const String PAYPAL = 'assets/country/paypal.png';
  static const String EMAIL_VERIFICATION = 'assets/email_verification.png';
  static const String IOSAPPICON = 'assets/iosappicon.jpg';
  static const String PLAYSTORE = 'assets/playstore.png';
}
