/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'next_wisher';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String APPSTORE = 'assets/appstore.png';
  static const String LOGO = 'assets/logo.png';
  static const String PLAYSTORE = 'assets/playstore.png';
  static const String WELCOME = 'assets/welcome.png';
}
