// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmQS2Vl-8NAQYo5Q3aXCObLUqH-r4FNKM',
    appId: '1:49411779568:android:8497bdc506ec0c866ecb35',
    messagingSenderId: '49411779568',
    projectId: 'fir-demo-c5451',
    storageBucket: 'fir-demo-c5451.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2sd83p9-lgZugLsYILZT8Pz6lK-VSnK8',
    appId: '1:49411779568:ios:9e0c94671658ca056ecb35',
    messagingSenderId: '49411779568',
    projectId: 'fir-demo-c5451',
    storageBucket: 'fir-demo-c5451.appspot.com',
    androidClientId: '49411779568-vqlril76skkp7a0shf52m9a862d78r4a.apps.googleusercontent.com',
    iosClientId: '49411779568-bopgrn16jg8445jimq0lmau3ukhnthel.apps.googleusercontent.com',
    iosBundleId: 'com.example.nextWisher',
  );
}
